import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faFile,
  faImage,
  faLock,
  faDatabase,
} from "@fortawesome/free-solid-svg-icons";
import {
  faJs,
  faRust,
  faPython,
  faJava,
  faRProject,
  faPhp,
  faMarkdown,
  faGolang,
  faCss3,
  faHtml5,
  faReact,
  faVuejs,
  faAngular,
  faNodeJs,
  faNpm,
  faGit,
  faSwift,
  faLinux,
} from "@fortawesome/free-brands-svg-icons";
const fileIconMap = {
  ".js": faJs,
  ".json": faJs,
  ".jsx": faReact,
  ".ts": faJs,
  ".tsx": faReact,
  ".rs": faRust,
  ".py": faPython,
  ".java": faJava,
  ".jar": faJava,
  ".class": faJava,
  ".r": faRProject,
  ".php": faPhp,
  ".md": faMarkdown,
  ".go": faGolang,
  ".css": faCss3,
  ".html": faHtml5,
  ".vue": faVuejs,
  ".angular": faAngular,
  ".node": faNodeJs,
  ".npm": faNpm,
  ".git": faGit,
  ".gitignore": faGit,
  ".swift": faSwift,
  ".sh": faLinux,
  ".lock": faLock,
  ".sql": faDatabase,
  ".sqlite": faDatabase,
  ".db": faDatabase,
  ".mdb": faDatabase,
  ".accdb": faDatabase,
  ".dbf": faDatabase,
  ".ibd": faDatabase,
  ".myd": faDatabase,
  ".myi": faDatabase,
  ".frm": faDatabase,
  ".ldb": faDatabase,
  ".sdb": faDatabase,
  ".svg": faImage,
  ".png": faImage,
  ".jpg": faImage,
  ".gif": faImage,
  ".webp": faImage,
  ".ico": faImage,
  ".icns": faImage,
  ".bmp": faImage,
  ".jpeg": faImage,
  ".tif": faImage,
  ".tiff": faImage,
  ".psd": faImage,
};

export default function FileIcon({ file }) {
  const extension = file.name.slice(file.name.lastIndexOf("."));
  const icon = fileIconMap[extension] || faFile;

  return <FontAwesomeIcon icon={icon} />;
}
